spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker
  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: docker

logging:
  level:
    com.bednar.dbexplorer: DEBUG
